### ISSUE TITLE
goNext,goPrevious don’t work in v1.99.5-v1.99.7

### ISSUE THREAD

**Issue by bruceye** [gdh1995/vimium-c#789]
no map change for [[ and ]], but when hit [[ or ]], nothing happened

firefox  106.05   
Vimium C 1.99.5
![微信截图_20221107113502](https://user-images.githubusercontent.com/10141208/200221223-37413e42-9c2f-47b4-a31d-a50249f9afd3.png)

**Comment by gdh1995** [comment]
Sorry for this bug. Duplicate of #787.

**Comment by bruceye** [comment]
version 1.99.3  work ok

**Comment by gdh1995** [comment]
hello, v1.99.6 has been published and you may take a try.

**Comment by bruceye** [comment]
v1.99.6 not work
and add an error--》unmap don't work
![截图_20221107182650](https://user-images.githubusercontent.com/10141208/200288102-64cee180-5823-4af7-8138-2674fde14a10.png)

**Comment by gdh1995** [comment]
@bruceye Um, just like what https://github.com/gdh1995/vimium-c/issues/787#issuecomment-1305404015 said? I've found my typo, and v1.99.7 will fix it. You may add `map d blank \n unmap d` to work it around temporarily

**Comment by gdh1995** [comment]
Hello, v1.99.7 for Firefox has been publishd, and you may take a try.

**Comment by bruceye** [comment]
unmap is ok
but goNext,goPrevious （[[ ,]]）still not work

**Comment by gdh1995** [comment]
Oh sorry, this issue is a different bug from #787. I was too exhausted to read your first comment carefully.

Then v1.99.8 is needed. Let me wait for 1~2 days to collect more portential bug reports.

**Comment by gdh1995** [comment]
There's a working around for this bug, by disabling some features of `goNext`:
```
map ]] goNext noRel
map [[ goPrevious noRel
```

With `noRel`, `goNext` may find less next URLs, so when a new version fixes it, please remove `noRel` to ensure it works as in v1.99.3.

**Comment by bg7lgb** [comment]
vimium 1.99.5 , chrome  107.0.5304.107,    not working.

vimium 1.99.3, edge  107.0.1418.35  , ok

**Comment by gdh1995** [comment]
Hello, v1.99.8 for Firefox has been published and the tricks to work around `(un)map` and `goNext` should not be needed any more.

**Comment by agzam** [comment]
The suggested workaround with:

    map ]] goNext noRel
    map [[ goPrevious noRel

Doesn't seem to have any effect in Brave. 

What's the proper way of installing an older version?
I wanted to rollback to 1.99.3 until this one gets fixed. I tried:

- Dowloaded vimium-c-1.99.3.zip from Assets
- Unpacked
- `npm install`
- `npx gulp dist` is failing with the following:
<details> <summary>errors</summary>

    [16:59:21] Using gulpfile ~/Downloads/vimium-c-1.99.3/vimium-c-1.99.3/gulpfile.js
    [16:59:21] Starting 'dist'...
    [16:59:21] Starting 'build/ts'...
    [16:59:21] Starting 'build/_all'...
    [16:59:21] Starting 'build/scripts'...
    [16:59:21] Starting 'build/pages'...
    [16:59:21] Starting 'build/background'...
    [16:59:21] Starting 'build/content'...
    [16:59:21] Starting 'build/front'...
    [16:59:21] Starting 'build/options'...
    [16:59:21] Starting 'build/show'...
    [16:59:21] Starting 'build/others'...
    [16:59:21] Get random seed: &t=1660923496000
    [16:59:22] Load the TypeScript dependency: succeed
    [16:59:22] Skip these TypeScript options: incremental, tsBuildInfoFile
    [16:59:26] Not transform ES6 generators
    content/link_hints.ts(687,21): error TS2345: Argument of type '(Function & BaseHintWorker) | (Function & (() => void))' is not assignable to parameter of type '(this: void, fake?: TimerType.fake | undefined) => void'.
    Type 'Function & BaseHintWorker' is not assignable to type '(this: void, fake?: TimerType.fake | undefined) => void'.
        Type 'Function & BaseHintWorker' provides no match for the signature '(this: void, fake?: TimerType.fake | undefined): void'.
    lib/rect.ts(195,23): error TS2339: Property 'coords' does not exist on type 'SafeHTMLElement | HTMLAreaElement'.
    Property 'coords' does not exist on type 'SafeHTMLElement'.
    lib/rect.ts(196,24): error TS2339: Property 'shape' does not exist on type 'SafeHTMLElement | HTMLAreaElement'.
    Property 'shape' does not exist on type 'SafeHTMLElement'.
    TypeScript: 3 semantic errors
    TypeScript: emit succeeded (with errors)
    [16:59:26] 'build/content' errored after 5.26 s
    [16:59:26] Error: TypeScript: Compilation failed
        at Output.mightFinish (/Users/ag/Downloads/vimium-c-1.99.3/vimium-c-1.99.3/node_modules/gulp-typescript/release/output.js:131:43)
        at /Users/ag/Downloads/vimium-c-1.99.3/vimium-c-1.99.3/node_modules/gulp-typescript/release/output.js:44:22
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
    [16:59:26] 'build/scripts' errored after 5.26 s
    [16:59:26] 'build/_all' errored after 5.26 s
    [16:59:26] 'build/ts' errored after 5.26 s
    [16:59:26] 'dist' errored after 5.27 s

</details>

tried on
node --version
v16.18.1

**Comment by gdh1995** [comment]
sorry, if you're in v1.99.5, you also need another trick of unmap:


unmap ]]
map ]] goNext noRel



---Original---
From: "Ag ***@***.***&gt;
Date: Wed, Nov 16, 2022 07:06 AM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] goNext,goPrevious don’t work in v1.99.5-v1.99.7 (Issue #789)




 
The suggested workaround with:
 map ]] goNext noRel map [[ goPrevious noRel  
Doesn't seem to have any effect in Brave.
 
What's the proper way of installing an older version?
 I wanted to rollback to 1.99.3 until this one gets fixed. I tried:
  
Dowloaded vimium-c-1.99.3.zip from Assets
 
Unpacked
 
npm install
 
npx gulp dist is failing with the following:
   errors [16:59:21] Using gulpfile ~/Downloads/vimium-c-1.99.3/vimium-c-1.99.3/gulpfile.js [16:59:21] Starting 'dist'... [16:59:21] Starting 'build/ts'... [16:59:21] Starting 'build/_all'... [16:59:21] Starting 'build/scripts'... [16:59:21] Starting 'build/pages'... [16:59:21] Starting 'build/background'... [16:59:21] Starting 'build/content'... [16:59:21] Starting 'build/front'... [16:59:21] Starting 'build/options'... [16:59:21] Starting 'build/show'... [16:59:21] Starting 'build/others'... [16:59:21] Get random seed: &amp;t=1660923496000 [16:59:22] Load the TypeScript dependency: succeed [16:59:22] Skip these TypeScript options: incremental, tsBuildInfoFile [16:59:26] Not transform ES6 generators content/link_hints.ts(687,21): error TS2345: Argument of type '(Function &amp; BaseHintWorker) | (Function &amp; (() =&gt; void))' is not assignable to parameter of type '(this: void, fake?: TimerType.fake | undefined) =&gt; void'. Type 'Function &amp; BaseHintWorker' is not assignable to type '(this: void, fake?: TimerType.fake | undefined) =&gt; void'.     Type 'Function &amp; BaseHintWorker' provides no match for the signature '(this: void, fake?: TimerType.fake | undefined): void'. lib/rect.ts(195,23): error TS2339: Property 'coords' does not exist on type 'SafeHTMLElement | HTMLAreaElement'. Property 'coords' does not exist on type 'SafeHTMLElement'. lib/rect.ts(196,24): error TS2339: Property 'shape' does not exist on type 'SafeHTMLElement | HTMLAreaElement'. Property 'shape' does not exist on type 'SafeHTMLElement'. TypeScript: 3 semantic errors TypeScript: emit succeeded (with errors) [16:59:26] 'build/content' errored after 5.26 s [16:59:26] Error: TypeScript: Compilation failed     at Output.mightFinish (/Users/ag/Downloads/vimium-c-1.99.3/vimium-c-1.99.3/node_modules/gulp-typescript/release/output.js:131:43)     at /Users/ag/Downloads/vimium-c-1.99.3/vimium-c-1.99.3/node_modules/gulp-typescript/release/output.js:44:22     at processTicksAndRejections (node:internal/process/task_queues:96:5) [16:59:26] 'build/scripts' errored after 5.26 s [16:59:26] 'build/_all' errored after 5.26 s [16:59:26] 'build/ts' errored after 5.26 s [16:59:26] 'dist' errored after 5.27 s   
tried on
 node --version
 v16.18.1

**Comment by gdh1995** [comment]
Hello, v1.99.90 has been released on Chrome Web Store, and you may take a try. All above tricks should not be needed any more.

**Comment by agzam** [comment]
Btw, since this is related, I think you may want to consider this feature to scan the elements from the bottom of the page. It often happens that many websites would have two sections with pageable navigation, e.g., Amazon, Google. It usually looks like thumbnails for things to review (goods to order, etc.) with prev/next navigation. Obviously, a user intends to use `]]` to navigate to the next page, but with pages like that, it scrolls to the next item in the top list.

What do you think?

**Comment by gdh1995** [comment]
Any example page URL? It's hard to make a big category work well on all websites, so `goNext` currently only prefers visible elements with fewer words.

`goNext` also supports `exclude` and `match` said in https://github.com/gdh1995/vimium-c/wiki/Add-or-remove-hints . And you may write some selectors to exclude unwanted items.

In fact, it has another mode to recognize page number from a page URL and jump to another directly - https://github.com/gdh1995/vimium-c/wiki/Substitute-URLs-and-text-during-commands#go-next-to-another-number
